name: docker-image-push-join

on:
  push:
    branches: [ main, cleanup-cicd ]
  
jobs:
  build:  
    uses: MukuFlash03/e-mission-server/.github/workflows/reusable_image_build_push.yml@cleanup-cicd
    with:
      repo: ${{ github.event.repository.name }}
      branch: ${{ github.ref_name }}
    secrets: inherit
